=== roadrunnerlenny/huntthenuts_wpf/HuntTheNuts/Levels/Level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="snake">
          <xs:complexType>
            <xs:attribute name="snakeStartPosX" type="xs:unsignedByte" use="required" />
            <xs:attribute name="snakeStartPosY" type="xs:unsignedByte" use="required" />
            <xs:attribute name="offsetY" type="xs:double" use="optional" />
            <xs:attribute name="filenameHead" type="xs:string" use="optional" />
            <xs:attribute name="filenameTail" type="xs:string" use="optional" />
            <xs:attribute name="filenameCollision" type="xs:string" use="optional" />
            <xs:attribute name="filenameWin" type="xs:string" use="optional" />
            <xs:attribute name="filenameGrow" type="xs:string" use="optional" />
            <xs:attribute name="filenameShrink" type="xs:string" use="optional" />
            <xs:attribute name="animated" type="xs:boolean" use="optional" />
            <xs:attribute name="animationFrames" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="collisionFrames" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="winFrames" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="growFrames" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="shrinkFrames" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="animationDelay" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="collisionDelay" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="winDelay" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="growDelay" type="xs:unsignedByte" use="optional" />
            <xs:attribute name="shrinkDelay" type="xs:unsignedByte" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element name="apples">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="apple">
                <xs:complexType>
                  <xs:attribute name="img" type="xs:string" use="optional" />
                  <xs:attribute name="offsetY" type="xs:double" use="optional" />
                  <xs:attribute name="points" type="xs:integer" use="required" />
                  <xs:attribute name="tailgrow" type="xs:unsignedByte" use="optional" />
                  <xs:attribute name="special" type="xs:boolean" use="optional" />
                  <xs:attribute name="type" type="xs:string" use="optional" />
                  <xs:attribute name="value" type="xs:integer" use="optional" />
                  <xs:attribute name="time" type="xs:integer" use="optional" />
                  <xs:attribute name="prob" type="xs:integer" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="objects">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="object" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="number" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="posX" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="posY" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="sizeX" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="sizeY" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="offsetY" type="xs:double" use="optional" />
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="filename" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="tileSize" type="xs:unsignedByte" use="optional" />
      <xs:attribute name="background" type="xs:string" use="optional" />
      <xs:attribute name="borderBackground" type="xs:string" use="optional" />
      <xs:attribute name="width" type="xs:unsignedByte" use="required" />
      <xs:attribute name="height" type="xs:unsignedByte" use="required" />
      <xs:attribute name="targetScore" type="xs:integer" use="required" />
      <xs:attribute name="startSpeed" type="xs:unsignedByte" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== roadrunnerlenny/huntthenuts_wpf/HuntTheNuts/Levels/Level4.xml
<?xml version="1.0" encoding="utf-8" ?>
<level xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Level.xsd"
       name="Level 4" tileSize="20" background="NutsTheme/grass_bg" borderBackground="NutsTheme/border_hedge" 
       width="20" height="10" startSpeed="5" targetScore="70">
  <snake snakeStartPosX="10" snakeStartPosY="8" offsetY="-13" filenameHead="NutsTheme/squirrel_animation" filenameTail="NutsTheme/squirrel_animation" 
         filenameCollision="NutsTheme/collision" filenameWin="NutsTheme/dance" filenameGrow="NutsTheme/grow" filenameShrink="NutsTheme/shrink"
         animated="True" animationFrames="4" animationDelay="2" 
         collisionFrames="7" collisionDelay="3" winFrames="5" winDelay="5" growFrames="2" growDelay="10" shrinkFrames="7" shrinkDelay="3" />
  <apples>
    <apple img="NutsTheme/nut" offsetY="-5" points="1" tailgrow="1" special="false" />
    <apple img="NutsTheme/nut" offsetY="-5" points="1" tailgrow="1" special="false" />
    <apple img="NutsTheme/nut" offsetY="-5" points="1" tailgrow="1" special="false" />
    <apple img="NutsTheme/nuts" offsetY="-5" points="2" tailgrow="2" special="true" type="normal" value="0" time="0" prob="50"/>
    <apple img="NutsTheme/nuts" offsetY="-5" points="2" tailgrow="2" special="true" type="normal" value="0" time="0" prob="50"/>
    <apple img="NutsTheme/poison_nut" offsetY="-5" points="-1" tailgrow="0" special="true" type="shrinking" value="2" time="0" prob="25"/>
    <apple img="NutsTheme/poison_nut" offsetY="-5" points="-1" tailgrow="0" special="true" type="shrinking" value="2" time="0" prob="25"/>
    <apple img="NutsTheme/tlc" offsetY="-5" points="5" tailgrow="0" special="true" type="inverse" value="0" time="5" prob="66"/>
    <apple img="NutsTheme/golden_nut" offsetY="-5" points="0" tailgrow="0" special="true" type="win" value="0" time="0" prob="0"/>

  </apples>
  <objects>
    <object number="1" posX="3" posY="3" sizeX="2" sizeY="2" offsetY="-27" name="Tree" filename="NutsTheme/tree" />
    <object number="2" posX="3" posY="6" sizeX="3" sizeY="3" offsetY="-32" name="Big Tree" filename="NutsTheme/tree3" />
    <object number="3" posX="15" posY="2" sizeX="2" sizeY="2" offsetY="-27" name="Tree" filename="NutsTheme/tree" />
    <object number="3" posX="16" posY="4" sizeX="2" sizeY="2" offsetY="-27" name="Tree" filename="NutsTheme/tree" />
    <object number="3" posX="17" posY="6" sizeX="2" sizeY="2" offsetY="-27" name="Tree" filename="NutsTheme/tree" />
    <object number="3" posX="7" posY="3" sizeX="2" sizeY="2" offsetY="-27" name="Tree" filename="NutsTheme/tree" />
    <object number="3" posX="9" posY="5" sizeX="1" sizeY="1" offsetY="-20" name="Sunflower" filename="NutsTheme/flower" />
    <object number="3" posX="12" posY="7" sizeX="1" sizeY="1" offsetY="-20" name="Sunflower" filename="NutsTheme/flower" />
  </objects>
</level>
